apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::242464191520:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1D2RR9SDUW2N1
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
          - system:masters
          rolearn: arn:aws:iam::242464191520:role/UdacityFlaskDeployCBKubectlRole
          username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-05-02T15:46:37Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "5679"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: bdd81a6e-a9c5-4fa2-af19-92c52b2e4abf
